In [1]:
import numpy as np
import pandas as pd

In [2]:
df_old = pd.read_csv('metadata_old.csv')
df_new = pd.read_csv('metadata_new.csv')

In [3]:
df_old.head()

,video_id,category,tag,title,description
0,994a5e59391f7cdcac87b83ac97df50d,Спорт,Экстрим,Кинул вызов команде DiMaTyArIk SCHOOL,Кинул вызов команде DiMaTyArIk SCHOOL
1,3525516efb0d30911e13829e3d5152e3,Спорт,Экстрим,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL
2,768929af55490246ed4b1496b9e98977,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
3,3df5d0c1f2e4a91c63cebffc14c8c467,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
4,162df7df705937f64947c2dd89605d10,Спорт,Экстрим,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2

In [4]:
df_new.head()

,video_id,category,tag,title,description
0,994a5e59391f7cdcac87b83ac97df50d,Спорт,Экстрим,Кинул вызов команде DiMaTyArIk SCHOOL,Кинул вызов команде DiMaTyArIk SCHOOL
1,3525516efb0d30911e13829e3d5152e3,Спорт,Экстрим,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL
2,768929af55490246ed4b1496b9e98977,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
3,3df5d0c1f2e4a91c63cebffc14c8c467,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
4,162df7df705937f64947c2dd89605d10,Спорт,Экстрим,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2

In [8]:
df_old.video_id.count()

np.int64(7620)

In [10]:
df_new.video_id.count()

np.int64(7220)

In [11]:
df_old.video_id.count() - df_new.video_id.count()

np.int64(400)

In [13]:
count = 0
for video_id in df_old.video_id.value_counts():
    if video_id > 1:
        count += 1
print(count)

345

In [16]:
df_old.category.value_counts()

category
Спорт                           200
Путешествия                     200
Люди и блоги                    200
Хобби                           200
Видеоигры                       200
Разное                          200
Лайфстайл                       200
Лайфхаки                        200
Телепередачи                    200
Юмор                            200
Авто-мото                       200
Сериалы                         200
Музыка                          200
Развлечения                     200
Обучение                        200
Фильмы                          200
Наука                           200
Новости и СМИ                   200
Технологии и интернет           200
Детям                           200
Красота                         200
Животные                        200
Политика                        200
Здоровье                        200
Мультфильмы                     200
Культура                        200
Еда                             200
Аниме                           200
Психология                      200
Техника и оборудование          200
Интервью                        200
Эзотерика                       200
Сад и огород                    200
Бизнес и предпринимательство    200
Строительство и ремонт          194
Обзоры и распаковки товаров     194
Аудиокниги                      112
Природа                          77
Охота и рыбалка                  70
Дизайн                           64
Религия                          60
Недвижимость                     30
Аудио                            19
Name: count, dtype: int64

In [14]:
df_new.category.value_counts()

category
Массовая культура                      1000
Фильмы и анимация                       800
Дом и сад                               458
Телевидение                             400
Информационные технологии               400
Новости и политика                      400
Музыка и аудио                          331
Путешествия                             277
Спорт                                   270
Транспорт                               200
Хобби и интересы, Массовая культура     200
Хобби и интересы                        200
Игры                                    200
Наука                                   200
Стиль и красота                         200
Животные                                200
Образование                             200
Бизнес и финансы                        200
Здоровый образ жизни                    200
Карьера                                 200
Еда и напитки                           200
Медицина                                200
Покупки                                 194
Религия и духовность                     60
Недвижимость                             30
Name: count, dtype: int64

In [24]:
df = pd.read_csv('../../data/metadata.csv')

In [25]:
df.tag.value_counts()

tag
Шоу талантов          75
Аниме                 70
Альтернативная        70
Rutube Shorts         67
Французский футбол    64
                      ..
Уличные тренировки     1
Готовим пиццу          1
В топе.Еда             1
В Топе.Спорт           1
60-е                   1
Name: count, Length: 1020, dtype: int64

In [26]:
df = df.dropna()

In [27]:
df = df.drop_duplicates()

In [28]:
df = df[(df != '').all(axis=1)]

In [29]:
len(np.unique(df['tag']))

1020

In [34]:
gp = pd.read_csv('../../data/graph.csv')

In [30]:
df.to_csv('../../data/metadata.csv', index=False)

In [35]:
gp

      source  target    weight
0          0       0  0.561114
1          0       1  0.681141
2          0       2  0.582779
3          0       3  0.622874
4          0       4  0.574955
...      ...     ...       ...
1953      42     973  0.446803
1954      42     989  0.597358
1955      42    1008  0.527321
1956      42    1010  0.618391
1957      42    1012  0.666661

[1958 rows x 3 columns]

In [36]:
len(np.unique(gp.target))

1007

In [37]:
gp.target.value_counts()

target
32      13
351     13
207     12
67      12
147     11
        ..
763      1
764      1
768      1
790      1
1012     1
Name: count, Length: 1007, dtype: int64

In [40]:
# Получить уникальные значения из колонки 'tag'
unique_subcategories = df['tag'].unique()

# Создать отображения: категория -> индекс
subcat2idx = {subcategory: idx for idx, subcategory in enumerate(unique_subcategories)}
idx2subcat = {idx: subcategory for idx, subcategory in enumerate(unique_subcategories)}

# Преобразовать колонку 'tag' в индексы
df_indices = df['tag'].map(subcat2idx)

# Найти значения, которые есть в column1 (df['tag']), но отсутствуют в column2 (gp['target'])
missing_in_column2 = set(df_indices) - set(gp['target'])
print("Значения из df, которых нет в gp:", missing_in_column2)

# Найти значения, которые есть в column2 (gp['target']), но отсутствуют в column1 (df['tag'])
missing_in_column1 = set(gp['target']) - set(df_indices)
print("Значения из gp, которых нет в df:", missing_in_column1)

Значения из df, которых нет в gp: {360, 924, 650, 682, 684, 301, 686, 979, 660, 695, 664, 508, 607}
Значения из gp, которых нет в df: set()

In [44]:
miser = []
for idx, mis in enumerate(missing_in_column2):
    miser.append(idx2subcat[mis])
print(miser)

['Аниме', 'Лайфстайл', 'Охота и рыбалка', 'Детям', 'Наука', 'Видеоигры', 'Лайфхаки', 'Недвижимость', 'Строительство и ремонт', 'Спорт', 'Психология', 'Интервью', 'Путешествия']

In [45]:
# Удаление строк, где 'tag' соответствует значениям из missing_in_gp
df_filtered = df[~df['tag'].isin(miser)]

In [46]:
df_filtered.tag.value_counts()

tag
Шоу талантов              75
Альтернативная            70
Rutube Shorts             67
Французский футбол        64
Лекторий                  63
                          ..
Буква Ы                    1
Скандал с Волочковой       1
Крещение 2022              1
Католическое Рождество     1
Тренды августа 2013        1
Name: count, Length: 1007, dtype: int64

In [47]:
df_filtered.to_csv('../../data/metadata.csv', index=False)